#!/bin/sh -xe

# Required so that MacOS does not drop some of our UDP packets
# It is a reasonably safe assumption that nobody else's application depends
# on the behavior of their packets getting silently dropped
sysctl net.inet.udp.maxdgram=65535

cat << EOF > /Library/LaunchDaemons/com.github.stargatedaw.stargate.launchdaemon.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>StargateDAW UDP Settings</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/sbin/sysctl</string>
		<string>net.inet.udp.maxdgram=65535</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
EOF

/bin/launchctl load "/Library/LaunchDaemons/com.github.stargatedaw.stargate.launchdaemon.plist" || true

