name: Stargate

on:
  workflow_dispatch

jobs:

  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: ./scripts/debian_deps.sh
    - name: Update git submodules
      run: git submodule init && git submodule update

    - name: Build
      run: ./scripts/deb.py && ./scripts/rpm.py --nodeps

    - name: DEB Upload
      uses: actions/upload-artifact@v2.2.4
      with:
        name: DEB package
        path: ./src/*.deb

    - name: RPM Upload
      uses: actions/upload-artifact@v2.2.4
      with:
        name: RPM package
        path: ./*.rpm
